### ISSUE TITLE
Roadmap: Reimplement KEYPAD as emacs input method

### ISSUE THREAD

**Issue by DogLooksGood** [meow-edit/meow#64]
# The Problem
Currently, the inputs in KEYPAD mode are handled by `keypad-self-insert` which is a command. There are two disadvantages:

1. Since keypad input is a single command, it will be record by KMacros. So you can call `kmacro-end-macro` <kbd>C-x )</kbd> by press <kbd>SPC x )</kbd> in KEYPAD, because there will be two inputs: <kbd>SPC x</kbd>(map to `keypad-start`) and <kbd>)</kbd>(map to `keypad-self-insert`).
2. Meow has to raise the priority for KEYPAD map since KEYPAD is designed not to be interrupted by any other packages. 

# The Ideas
We can implement KEYPAD state as an input method in Emacs. An input method won't produce any key events until you finish your input. This will improve the compatibility of KEYPAD mode, make it work better with other packages. It may have some limitations, need some time to figure it out.
- Input method won't handle all keys probably

# The Solution
TBD

**Comment by DogLooksGood** [comment]
It seems that input method does not support input event like `^X^F`. Only list of numbers are supported.
 
Probably it's possible with `input-decode-map`.

**Comment by DogLooksGood** [comment]
Close for now.

**Comment by DogLooksGood** [comment]
```
(defun keypad-handle-input (key)
  (message "key: %s ---" key)
  (append (kbd "C-x C-f") nil))

(defun keypad-activate (_name)
  (setq-local input-method-function 'keypad-handle-input))

(register-input-method "keypad" "euc-en"
		       'keypad-activate
		       "K")
```

It seems to be possible to simulate arbitrary input with input method.

**Comment by DogLooksGood** [comment]
Give up!

**Comment by fbergroth** [comment]
What issues did you run into? Would it still be desirable to implement keypad using an input method if those issues were fixed?

**Comment by DogLooksGood** [comment]
The input method will only receive input when there's no pending input. 
For example, the input method can translate x to C-x, but following keys will not be received.

If we keep all inputs, only emit the output when keypad found a command, the kmacro recording will still receive the input key.
Then SPC x f will becomes SPC x f C-x C-f.

**Comment by fbergroth** [comment]
I see, thanks. I see you mentioned `input-decode-map` as well. Could it be solved with event translation keymaps, or did you face some other problems using that?

**Comment by DogLooksGood** [comment]
I just try it briefly, it seems that an input can not be prevented by `input-decode-map`. 
So, I don't know how to implement literal prefix (`SPC`) with it.

The `M-` is just `ESC`, and `C-M-` is `ESC C-`. It seems that the only problem is literal prefix.

**Comment by fbergroth** [comment]
Could it be solved by returning the next event?
```
(defun meow--pass-thru-event (_prompt)
  (vector (read-event)))

(define-key input-decode-map " " 'meow--pass-thru-event)
```

**Comment by DogLooksGood** [comment]
Test with `F3 SPC p F4`, the recorded macro is `SPC p`, we want it to be `p`.

**Comment by fbergroth** [comment]
But in meow it will look like `F3 SPC SPC p F4`, where the first SPC will call `meow-keypad`, which will setup the keyboard translations. Won't the same key translations be done when executing the macro?

**Comment by DogLooksGood** [comment]
Yes, unless you end recording with `SPC x k k`. Then the macro ends with `SPC x k`, the last `k` is dropped.

**Comment by fbergroth** [comment]
@DogLooksGood this seems to work, what do you think:
```
(defun meow-kp--read-event (prefix)
  (cl-loop
   with mods = '(control)
   with mods-str = "C-"
   for ev = (read-key (concat prefix mods-str))
   if (eq ev ?g)       do (setq mods '(control meta) mods-str "C-M-")
   else if (eq ev ?m)  do (setq mods '(meta)         mods-str "M-")
   else if (eq ev ?\s) do (setq mods nil             mods-str "")
   else return (event-convert-list (append mods (list ev)))))

(defun meow-kp (_ignore)
  (if (not (and meow-mode (member meow--current-state '(normal motion))))
      [?\s]
    (let ((meow--current-state 'keypad)
          (events [])
          (pending t)
          (prefix "KEYPAD: "))
      (while pending
        (setq events (vconcat events (list (meow-kp--read-event prefix)))
              prefix (format "KEYPAD: %s " (key-description events)))
        (let ((target (lookup-key global-map events)))
          (when (or (null target)
                    (integerp target)
                    (commandp target))
            (setq pending nil))))
      events)))

(define-key key-translation-map (kbd "SPC") 'meow-kp)
```
Indicators should be easy to add. Some details are missing, such as fallback etc, but should be doable.

**Comment by DogLooksGood** [comment]
I also have a version, by set parent map for key-translation-map. Will this work with which-key?

**Comment by fbergroth** [comment]
Probably this requires a shim that calls `which-key--create-buffer-and-show`.

I also thought about filling `key-translation-map` with all keys. which-key should work without a shim that way, but it wasn't obvious to me how to do the setup and cleanup of key-translation-map.

**Comment by DogLooksGood** [comment]
```

(defvar meow-keypad-start-translation-keys '(?x ?g ?h ?m ?c)
  "A list of keys to start input translation.")

(defvar meow-keypad-meta-prefix ?m)
(defvar meow-keypad-ctrl-meta-prefix ?g)
(defvar meow-keypad-literal-prefix 32)

(defvar meow-keypad-after-translation-setup-hook nil
  "A list of functions runs after `translation-key-map' is modified by KEYPAD state.

Function will receive one symbol argument, the translation type, can be ctrl, meta or nil.")

(defun meow--keypad-set-translation-parent (parent)
  (set-keymap-parent key-translation-map parent))

(defun meow-keypad-init ()
  (run-hook-with-args 'meow-keypad-after-translation-setup-hook 'ctrl)
  (meow--keypad-set-translation-parent meow-keypad-default-map))

(defun meow-keypad-exit ()
  (interactive)
  (run-hook-with-args 'meow-keypad-after-translation-setup-hook 'nil)
  (meow--keypad-set-translation-parent nil))

(defun meow--keypad-modify-next-input-with-default (_)
  (meow--keypad-set-translation-parent meow-keypad-default-map)
  (run-hook-with-args 'meow-keypad-after-translation-setup-hook 'ctrl)
  (kbd ""))

(defun meow--keypad-modify-next-input-with-literal (_)
  (meow--keypad-set-translation-parent meow-keypad-literal-map)
  (run-hook-with-args 'meow-keypad-after-translation-setup-hook nil)
  (kbd ""))

(defun meow--keypad-modify-next-input-with-meta (_)
  (meow--keypad-set-translation-parent meow-keypad-meta-map)
  (run-hook-with-args 'meow-keypad-after-translation-setup-hook 'meta)
  (kbd ""))

(defun meow--keypad-modify-next-input-with-meta (_)
  (meow--keypad-set-translation-parent meow-keypad-ctrl-meta-map)
  (run-hook-with-args 'meow-keypad-after-translation-setup-hook 'ctrl-meta)
  (kbd ""))

(progn
  (global-set-key (kbd "C-x C-, C-M-x") 'forward-char)
  (global-set-key (kbd "C-x C-, M-x") 'forward-char)
  (global-set-key (kbd "C-x C-, x") 'forward-char)
  (global-set-key (kbd "C-x C-, C-x") 'forward-char))

(defun meow--keypad-translate-default (_)
  (let* ((events (vector (event-apply-modifier last-input-event 'control 26 "C-")))
         (keys (vconcat (seq-take (this-command-keys)
                                  (1- (length (this-command-keys))))
                        events)))
    (if (key-binding keys)
        events
      (vector last-input-event))))

(defun meow--keypad-translate-meta (_)
  (meow--keypad-modify-next-input-with-default _)
  (let* ((events (vector (event-apply-modifier last-input-event 'meta 27 "M-")))
         (keys (vconcat (seq-take (this-command-keys)
                                  (1- (length (this-command-keys))))
                        events)))
    (if (key-binding keys)
        events
      (vector last-input-event))))

(defun meow--keypad-translate-ctrl-meta (_)
  (meow--keypad-modify-next-input-with-default _)
  (let* ((events (vector (thread-first
                           last-input-event
                           (event-apply-modifier 'control 26 "C-")
                           (event-apply-modifier 'meta 27 "M-"))))
         (keys (vconcat (seq-take (this-command-keys)
                                  (1- (length (this-command-keys))))
                        events)))
    (if (key-binding keys)
        events
      (vector last-input-event))))

(defun meow--keypad-translate-literal (_)
  (meow--keypad-modify-next-input-with-default _)
  nil)

(defvar meow-keypad-default-map
  (let ((keymap (make-keymap)))
    (let ((i ?\s))
      (while (< i 256)
	(define-key keymap (vector i) 'meow--keypad-translate-default)
	(setq i (1+ i))))
    (define-key keymap (vector meow-keypad-meta-prefix) 'meow--keypad-modify-next-input-with-meta)
    (define-key keymap (vector meow-keypad-ctrl-meta-prefix) 'meow--keypad-modify-next-input-with-ctrl-meta)
    (define-key keymap (vector meow-keypad-literal-prefix) 'meow--keypad-modify-next-input-with-literal)
    keymap)
  "Used as a parent keymap for `key-translation-map' in KEYPAD state.")

(defvar meow-keypad-meta-map
  (let ((keymap (make-keymap)))
    (let ((i ?\s))
      (while (< i 256)
	(define-key keymap (vector i) 'meow--keypad-translate-meta)
	(setq i (1+ i))))
    keymap)
  "Used as a parent keymap for `key-translation-map' when meta prefix is used in KEYPAD state.")

(defvar meow-keypad-ctrl-meta-map
  (let ((keymap (make-keymap)))
    (let ((i ?\s))
      (while (< i 256)
	(define-key keymap (vector i) 'meow--keypad-translate-ctrl-meta)
	(setq i (1+ i))))
    keymap)
  "Used as a parent keymap for `key-translation-map' when ctrl-meta prefix is used in KEYPAD state.")

(defvar meow-keypad-literal-map
  (let ((keymap (make-keymap)))
    (let ((i ?\s))
      (while (< i 256)
	(define-key keymap (vector i) 'meow--keypad-translate-literal)
	(setq i (1+ i))))
    keymap)
  "Used as a parent keymap for `key-translation-map' when literal prefix is used in KEYPAD state.")

(defun meow--keypad-which-setup (type)
  (let ((modifed-rep '(("\\`\\(.+ \\)?[[:graph:]]\\'") . t))
        (ctrl-rep '(("\\`\\(?:.+ \\)?C-\\([[:graph:]]\\)\\'") . ("\\1")))
        (meta-rep '(("\\`\\(?:.+ \\)?M-\\([[:graph:]]\\)\\'") . ("\\1")))
        (ctrl-meta-rep '(("\\`\\(?:.+ \\)?C-M-\\([[:graph:]]\\)\\'") . ("\\1"))))
    (cond
     ((eq 'ctrl type)
      (add-to-list 'which-key-replacement-alist modifed-rep)
      (add-to-list 'which-key-replacement-alist ctrl-rep))
     ((eq 'meta type)
      (add-to-list 'which-key-replacement-alist modifed-rep)
      (add-to-list 'which-key-replacement-alist meta-rep)
      (which-key--update))
     ((eq 'ctrl-meta type)
      (add-to-list 'which-key-replacement-alist modifed-rep)
      (add-to-list 'which-key-replacement-alist modifed-rep)
      (which-key--update))
     ((null type)
      (setq which-key-replacement-alist
            (thread-last
              which-key-replacement-alist
              (remove modifed-rep)
              (remove ctrl-rep)
              (remove meta-rep)
              (remove ctrl-meta-rep)))
      (which-key--update)))))

(add-hook 'meow-keypad-after-translation-setup-hook 'meow--keypad-which-setup)

(global-set-key (kbd "<f5>")
		(lambda ()
		  (interactive)
		  (message "enable")
		  (meow-keypad-init)))

(global-set-key (kbd "<f6>") #'meow-keypad-exit)
```
What I have at the moment.

**Comment by DogLooksGood** [comment]
By setting the parent of `key-translation-map`, can easily setup and cleanup.

**Comment by fbergroth** [comment]
I saw you wrote
> Since there are very few benefits, I'd like to stick with current implementation at the moment.

I don't like the popup or which-key, and prefer to `(setq prefix-help-command #'embark-prefix-help-command)`. Then you can hit `C-h` and get a completing-read interface for the keymap. This works with my implementation above (and likely what you pasted too, I haven't tested it), but not with the current keypad implementation. I might try to make a PR, or just keep using my version locally.

**Comment by DogLooksGood** [comment]
Hi, PR is welcomed, but must cover existing features.
